### ISSUE TITLE
jenkins插件

### ISSUE THREAD

**Issue by chauncyman** [XmirrorSecurity/OpenSCA-cli#11]
后续有考虑以Jenkins插件形式运行吗

**Comment by Xmirror-DevSecOps** [comment]
我们会在后续的迭代版本中支持Jenkins插件形式检测，也会逐步支持更多的检测场景，您可以关注OpenSCA社区公众号，或加入OpenSCA社区交流群，获取OpenSCA最新动态~感谢您的提议！

**Comment by StayTherapy** [comment]
Jenkins 插件已经可以下载了，请问接入文档吗？
