### ISSUE TITLE
if support other online vunerability database?

### ISSUE THREAD

**Issue by jenningsloy318** [XmirrorSecurity/OpenSCA-cli#121]
Hi,

At present, only one online databse is supported, do you have further plan to use other one line database ?

**Comment by SuperChen-CC** [comment]
Supporting multiple data sources requires us to provide additional compatibility for different metadata formats. 
A current compromise solution is to use [local data sources](https://github.com/XmirrorSecurity/OpenSCA-cli#explanations-of-vulnerability-database-fields) to synchronize data from other online vulnerability databases. 
If necessary, we can reopen this thread in the future. Thank you for your support.
