### ISSUE TITLE
没有漏洞库规则没法用吧，我觉得至少得开放那么几个作为demo吧。

### ISSUE THREAD

**Issue by 78778443** [XmirrorSecurity/OpenSCA-cli#2]
云平台官方有demo地址么，想试用也得有联系方式吧。

**Comment by Xmirror-DevSecOps** [comment]
> 云平台官方有demo地址么，想试用也得有联系方式吧。

云平台官方地址可访问[https://opensca.xmirror.cn](https://opensca.xmirror.cn/)
目前OpenSCA提供了本地漏洞库demo（[db-demo.json](https://github.com/XmirrorSecurity/OpenSCA-cli/blob/master/db-demo.json)），demo中的漏洞数据主要包含了Apache log4j2的漏洞信息。
如有问题，欢迎随时与我们沟通~

微信公众号：OpenSCA社区
技术交流微信群：加悬小镜微信（**13269936782**手机号同微信号）拉您进群
技术交流QQ群：832039395

**Comment by baihuhao2007** [comment]
您好，我在尝试使用本地漏洞库demo（db-demo.json）时无法生成out.json文件，log日志中也没有报错信息，请问是哪里出问题了呢
![image](https://user-images.githubusercontent.com/79696420/153135648-47929e61-a5a4-44fd-aa40-719e26511f26.png)
![微信图片_20220209144250](https://user-images.githubusercontent.com/79696420/153136115-cb5d59bd-bc0c-4ea0-8921-4de46f0539b3.png)

**Comment by Xmirror-DevSecOps** [comment]
close issue
