### ISSUE TITLE
支持对镜像sbom的扫描

### ISSUE THREAD

**Issue by b1cat** [XmirrorSecurity/OpenSCA-cli#296]
使用syft生成sbom文件上传到无结果

<img width="1160" alt="image" src="https://github.com/XmirrorSecurity/OpenSCA-cli/assets/30470078/84fe79b0-cdff-4a67-a601-7c9c3c69503d">

**Comment by SuperChen-CC** [comment]
感谢您的建议，当前 OpenSCA SaaS 免费版暂无计划提供此类知识库，如有需要可联系社区运营了解商业版，或重新打开问题继续讨论，谢谢。
