### ISSUE TITLE
release

### ISSUE THREAD

**Issue by 12089897411** [XmirrorSecurity/OpenSCA-cli#31]
下载可执行文件后，设置了本地漏洞库，但感觉还是从云端检测的

**Comment by itxiaohu001** [comment]
是否加了url和token参数，有这两个参数会优先从云端检测的。

**Comment by itxiaohu001** [comment]
> 下载可执行文件后，设置了本地漏洞库，但感觉还是从云端检测的

是否加了url和token参数？有这两个参数的话会优先从云端检测的。
