### ISSUE TITLE
能否支持对项目中的开源组件进行开源协议扫描

### ISSUE THREAD

**Issue by hmlu** [XmirrorSecurity/OpenSCA-cli#41]
能否支持对项目中的开源组件进行开源协议扫描，比如我们的产品售卖，对产品中使用的开源组件需要进行开源协议的合规性扫描。

**Comment by Qiuyue1111** [comment]
您好~这个功能目前已在内部测试阶段，很快就会支持上啦~

**Comment by Qiuyue1111** [comment]
您好，新发布的1.0.12版本已支持在JSON报告、SPDX标准格式SBOM中输出许可证信息。
