### ISSUE TITLE
什么时候能提供本地漏洞库呢

### ISSUE THREAD

**Issue by pubil** [XmirrorSecurity/OpenSCA-cli#42]

**Comment by Qiuyue1111** [comment]
您好~这块目前在规划中，会优先支持多种漏洞库格式的兼容，然后再开放本地库。到时候会通过仓库、公众号等渠道发布相关信息~

**Comment by Qiuyue1111** [comment]
您好~这块目前在规划中，会优先支持多种漏洞库格式的兼容，然后再开放本地库。到时候会通过仓库、公众号等渠道发布相关信息
