### ISSUE TITLE
OpenSca扫描文件数量超过1800个之后直接卡死

### ISSUE THREAD

**Issue by fulln** [XmirrorSecurity/OpenSCA-cli#43]
path 直接指定的项目的文件夹, 包括了多个子模块, 现在一直在scan dir 上面转圈圈

**Comment by Qiuyue1111** [comment]
您好~
通常情况下文件数量较多的时候确实会影响解析速度；您可以看下日志文件，如果还在写入的话说明工具还在正常执行解析，可以等等看；
另外JS的node_modules文件会对检出速度有比较明显的影响，我们内部也在研究这部分逻辑的优化方案

**Comment by fulln** [comment]
目前情况是，如果文件数量超过16w ，文件夹数量超过1830个  项目将处于一个永远在查询的状态

**Comment by Qiuyue1111** [comment]
了解，这块我们内部尽快复现下，研究下优化方案。
另外可能有帮助的一点就是工具本身解析的对象是特征文件，如果方便的话可以直接扫描完整的特征文件试试~
