### ISSUE TITLE
可以检测不同语言的代码片段吗

### ISSUE THREAD

**Issue by qrcarry** [XmirrorSecurity/OpenSCA-cli#47]

**Comment by Qiuyue1111** [comment]
您好，目前开源工具检测走得是包管理器逻辑，解析的对象是特征文件；
您的检测对象中可以包含不同语言的代码，但需要有对应的特征文件。

**Comment by qrcarry** [comment]
好的 谢谢您的解答 那目前对间接依赖的检测好像还不太清晰对吗



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月21日 21:35 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [XmirrorSecurity/OpenSCA-cli] 可以检测不同语言的代码片段吗 (Issue #47) |

您好，目前开源工具检测走得是包管理器逻辑，解析的对象是特征文件；
您的检测对象中可以包含不同语言的代码，但需要有对应的特征文件。

**Comment by Qiuyue1111** [comment]
工具逻辑是通过特征文件做第一层解析，此后访问中央仓库获取完整的依赖信息；间接依赖是会全部检出的~
