### ISSUE TITLE
" You need to enable JavaScript to run this app."为什么回出现这种情况?

### ISSUE THREAD

**Issue by JeakinsCheung** [XmirrorSecurity/OpenSCA-cli#5]
![image](https://user-images.githubusercontent.com/57223351/150294704-1e7f6a40-db56-446d-881a-83e6f8aa9dbc.png)
d
点击启动的时候出现如图情况如何解决

**Comment by Xmirror-DevSecOps** [comment]
不是插件本身的问题，可以试下重装开发工具。
