### ISSUE TITLE
您好，我在尝试使用本地漏洞库demo（db-demo.json）时无法生成out.json文件，log日志中也没有报错信息，请问是哪里出问题了呢

### ISSUE THREAD

**Issue by baihuhao2007** [XmirrorSecurity/OpenSCA-cli#6]
您好，我在尝试使用本地漏洞库demo（db-demo.json）时无法生成out.json文件，log日志中也没有报错信息，请问是哪里出问题了呢
![微信图片_20220209144250](https://user-images.githubusercontent.com/79696420/153140739-a7d8c6ba-74f2-48b6-b553-be54e80c59bf.png)
![image](https://user-images.githubusercontent.com/79696420/153140766-a2104c84-4e88-4add-874a-ec4859098e04.png)

**Comment by Xmirror-DevSecOps** [comment]
token和path的参数写错了，参数说明里的“${token}”和“${path}”代表的是变量，用的时候不需要"${}",且path需要指向你要检测的项目文件夹路径或者压缩文件路径
