### ISSUE TITLE
分析javascript项目时报错

### ISSUE THREAD

**Issue by x1aochuan** [XmirrorSecurity/OpenSCA-cli#8]
报错信息

`
[WARNING] 2022/03/16 19:13:45 package_json.go:142: improper constraint:
[WARNING] 2022/03/16 19:13:47 package_json.go:142: improper constraint:
[WARNING] 2022/03/16 19:13:48 package_json.go:142: improper constraint:
[WARNING] 2022/03/16 19:13:48 package_json.go:142: improper constraint:
[WARNING] 2022/03/16 19:13:48 package_json.go:142: improper constraint:
[WARNING] 2022/03/16 19:17:34 package_json.go:142: improper constraint:
[WARNING] 2022/03/16 19:17:35 package_json.go:142: improper constraint:
[WARNING] 2022/03/16 19:17:35 package_json.go:142: improper constraint:
[WARNING] 2022/03/16 19:17:35 package_json.go:142: improper constraint:
[WARNING] 2022/03/16 19:17:37 package_json.go:142: improper constraint:
`

**Comment by luotianqi777** [comment]
在处理版本约束时使用了旧版本(`1.5.0`)的`github.com/Masterminds/semver`库，升级版本后(`3.1.1`)可修复该问题

**Comment by luotianqi777** [comment]
在处理版本约束时使用了旧版本(`1.5.0`)的`github.com/Masterminds/semver`库，升级版本后(`3.1.1`)可修复该问题

**Comment by x1aochuan** [comment]
![image](https://user-images.githubusercontent.com/97670155/159433465-fc9ef1e6-e9ad-41e6-af98-25ec727f27b8.png)
使用新版本还是出现此问题

**Comment by Cattiie** [comment]
解决该问题尚未发版，请关注版本更新

**Comment by x1aochuan** [comment]
本地如何进行编译打包

**Comment by x1aochuan** [comment]
已经解决
